/**
 * Regenerates lib/catalog.dart — the offline fallback catalogue the app shows
 * before, or without, the live /data/catalog.json.
 *
 *   node scripts/gen_catalog.mjs            # from the live site
 *   node scripts/gen_catalog.mjs <file>     # from a local catalog.json
 *
 * The file's header had long pointed at a gen_catalog.mjs that was no longer in
 * the repo, and the baked list had fallen to 154 datasets against 227 live. A
 * first launch with no signal showed a catalogue two months old.
 */
import { readFile, writeFile } from 'node:fs/promises';

const SRC = process.argv[2];
const data = SRC
  ? JSON.parse(await readFile(SRC, 'utf8'))
  : await (await fetch('https://azenha.ai/bulldozer/data/catalog.json')).json();
if (!Array.isArray(data) || data.length < 150) throw new Error(`catalogue looks wrong: ${data.length} entries`);

const q = (s) => `'${String(s ?? '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$')}'`;
const rows = [...data]
  .sort((a, b) => String(a.title).localeCompare(String(b.title)))
  .map((e) => `  CatalogEntry(${[e.slug, e.title, e.unit, e.kind, e.topic, e.source, e.parsedAt, e.latest, e.firstSeen].map(q).join(', ')}),`);

const dart = `// GENERATED by scripts/gen_catalog.mjs from the BullDozer site's catalog.json — do not edit by hand.
// Regenerate: node scripts/gen_catalog.mjs
// This is the OFFLINE FALLBACK; at runtime the app loads the live catalog from
// /data/catalog.json (see catalog_store.dart).
class CatalogEntry {
  final String slug;
  final String title;
  final String unit;
  final String kind; // 'survey' | 'macro'
  final String topic;
  final String source;
  final String parsedAt; // ISO date the dataset was last RE-parsed (freshness, not arrival)
  final String latest; // latest data period present, e.g. "2024"
  final String firstSeen; // ISO date the dataset first appeared on the site
  const CatalogEntry(this.slug, this.title, this.unit, this.kind, this.topic,
      this.source,
      [this.parsedAt = '', this.latest = '', this.firstSeen = '']);
}

const List<CatalogEntry> bakedCatalog = [
${rows.join('\n')}
];
`;
await writeFile(new URL('../lib/catalog.dart', import.meta.url), dart);
console.log(`✓ lib/catalog.dart: ${rows.length} datasets, ${data.filter((e) => e.firstSeen).length} with firstSeen`);
